### ISSUE TITLE
New Relic for Node.js halted startup due to an error

### ISSUE THREAD

**Issue by jackkeller** [motepair/motepair-server#2]
Initial install, and running the server.

```
Error: Not starting without license key!
    at cb_nextTick (/Users/masked_username/workspace/motepair-server/node_modules/newrelic/lib/agent.js:161:16)
    at /Users/masked_username/workspace/motepair-server/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

Obviously the issue is not having a New Relic account, the code I'm wanting to pair on with a teammate is not allowed outside of our internal network, is there a way to just use one of our machines as the server and not need to leave the network?

**Comment by luizbafilho** [comment]
@jackkeller You are right that is because you have no new relic keys defined in your environment, but don't worry the app is still working fine, that is just a warning.

And yes, you just need to run the server in one machine and go to Motepair settings and put your IP there. The default server port is 3000, so, make sure to set that on settings too.

If you wanna change the port, you just need to set a variable when running the server

```
PORT=2000 nodejs target/server.js
```

If you have any questions, just ask.
